SET SERVEROUTPUT ON;

CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Action VARCHAR2(50),
    LogDate DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    (TransactionID, AccountID, Action, LogDate)
    VALUES
    (:NEW.TransactionID,
     :NEW.AccountID,
     'Transaction Inserted',
     SYSDATE);
END;
/

-- Test the trigger
INSERT INTO Transactions
VALUES
(3, 1, SYSDATE, 500, 'Deposit');

COMMIT;

SELECT * FROM AuditLog;